
CREATE TABLE roles (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) UNIQUE NOT NULL);
CREATE TABLE permissions (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(80) UNIQUE NOT NULL);
CREATE TABLE role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY(role_id, permission_id));
CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(180) UNIQUE NOT NULL, pass_hash VARCHAR(220) NOT NULL, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, phone VARCHAR(30), role_id INT NOT NULL, status VARCHAR(40) NOT NULL, created_at DATETIME, updated_at DATETIME);
CREATE TABLE user_sessions (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, refresh_hash VARCHAR(220), expires_at DATETIME);
CREATE TABLE password_reset_tokens (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, reset_hash VARCHAR(220), expires_at DATETIME);
CREATE TABLE worker_registration_requests (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, status VARCHAR(30), decision_reason TEXT, created_at DATETIME);
CREATE TABLE workers (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT UNIQUE NOT NULL, run VARCHAR(20) UNIQUE NOT NULL, internal_code VARCHAR(30) UNIQUE NOT NULL, section_id INT NOT NULL, position_id INT NOT NULL, contract_type_id INT NOT NULL, status VARCHAR(30), hired_at DATE, terminated_at DATE);
CREATE TABLE worker_personal_data (id INT PRIMARY KEY AUTO_INCREMENT, worker_id INT NOT NULL, address VARCHAR(240), emergency_contact VARCHAR(160));
CREATE TABLE contract_types (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) UNIQUE NOT NULL);
CREATE TABLE worker_statuses (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) UNIQUE NOT NULL);
CREATE TABLE sections (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(80) UNIQUE NOT NULL, active BOOLEAN DEFAULT TRUE);
CREATE TABLE positions (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) UNIQUE NOT NULL);
CREATE TABLE worker_points_history (id INT PRIMARY KEY AUTO_INCREMENT, worker_id INT NOT NULL, points INT NOT NULL CHECK(points BETWEEN 6 AND 20), valid_from DATE NOT NULL, valid_to DATE, reason VARCHAR(240));
CREATE TABLE worker_contract_history (id INT PRIMARY KEY AUTO_INCREMENT, worker_id INT NOT NULL, contract_type_id INT NOT NULL, valid_from DATE NOT NULL, valid_to DATE);
CREATE TABLE periods (id INT PRIMARY KEY AUTO_INCREMENT, year INT NOT NULL, month INT NOT NULL, status VARCHAR(30), UNIQUE(year, month));
CREATE TABLE calendar_days (id INT PRIMARY KEY AUTO_INCREMENT, day_date DATE UNIQUE NOT NULL, period_id INT NOT NULL, mandatory_calculation BOOLEAN DEFAULT TRUE);
CREATE TABLE shift_types (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) UNIQUE NOT NULL);
CREATE TABLE shift_statuses (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) UNIQUE NOT NULL);
CREATE TABLE shifts (id INT PRIMARY KEY AUTO_INCREMENT, worker_id INT NOT NULL, shift_date DATE NOT NULL, shift_type VARCHAR(30), status VARCHAR(30), start_time VARCHAR(10), end_time VARCHAR(10), worked_minutes INT, void_reason TEXT, UNIQUE(worker_id, shift_date, shift_type));
CREATE TABLE shift_claim_statuses (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) UNIQUE NOT NULL);
CREATE TABLE shift_claims (id INT PRIMARY KEY AUTO_INCREMENT, worker_id INT NOT NULL, claimed_date DATE NOT NULL, description TEXT NOT NULL, status VARCHAR(30), resolution TEXT);
CREATE TABLE daily_tip_funds (id INT PRIMARY KEY AUTO_INCREMENT, tip_date DATE UNIQUE NOT NULL, amount_clp INT NOT NULL CHECK(amount_clp >= 0), point_value_clp DECIMAL(12,2) DEFAULT 0, status VARCHAR(30), notes TEXT);
CREATE TABLE daily_tip_calculations (id INT PRIMARY KEY AUTO_INCREMENT, tip_date DATE UNIQUE NOT NULL, total_points INT, total_amount_clp INT, total_payable_clp INT, total_remainder_clp DECIMAL(12,2), calculated_at DATETIME);
CREATE TABLE daily_tip_calculation_details (id INT PRIMARY KEY AUTO_INCREMENT, calculation_id INT NOT NULL, worker_id INT NOT NULL, points_used INT NOT NULL, eligible BOOLEAN, raw_amount_clp DECIMAL(12,2), payable_amount_clp INT, rounding_remainder_clp DECIMAL(12,2));
CREATE TABLE rounding_remainders (id INT PRIMARY KEY AUTO_INCREMENT, period_id INT NOT NULL, source_date DATE NOT NULL, amount_clp DECIMAL(12,2), status VARCHAR(30));
CREATE TABLE monthly_closures (id INT PRIMARY KEY AUTO_INCREMENT, period_id INT NOT NULL, status VARCHAR(30), total_gross_clp INT, total_payable_clp INT, total_advances_clp INT, total_remainder_clp DECIMAL(12,2), carried_remainder_clp DECIMAL(12,2), closed_by INT, closed_at DATETIME);
CREATE TABLE monthly_closure_details (id INT PRIMARY KEY AUTO_INCREMENT, closure_id INT NOT NULL, worker_id INT NOT NULL, gross_clp INT, advances_clp INT, net_clp INT);
CREATE TABLE advance_request_statuses (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) UNIQUE NOT NULL);
CREATE TABLE advance_requests (id INT PRIMARY KEY AUTO_INCREMENT, worker_id INT NOT NULL, period_id INT NOT NULL, amount_clp INT NOT NULL, reason TEXT NOT NULL, status VARCHAR(30), decision_reason TEXT, requested_at DATETIME);
CREATE TABLE advance_decisions (id INT PRIMARY KEY AUTO_INCREMENT, advance_request_id INT NOT NULL, decided_by INT NOT NULL, decision VARCHAR(30), reason TEXT, decided_at DATETIME);
CREATE TABLE payment_statuses (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) UNIQUE NOT NULL);
CREATE TABLE payments (id INT PRIMARY KEY AUTO_INCREMENT, worker_id INT NOT NULL, period_id INT NOT NULL, gross_amount_clp INT, advance_discount_clp INT, adjustment_amount_clp INT, net_amount_clp INT, paid_amount_clp INT, status VARCHAR(30), paid_at DATETIME, paid_by INT);
CREATE TABLE payment_details (id INT PRIMARY KEY AUTO_INCREMENT, payment_id INT NOT NULL, concept VARCHAR(80), amount_clp INT NOT NULL);
CREATE TABLE worker_balances (id INT PRIMARY KEY AUTO_INCREMENT, worker_id INT NOT NULL, period_id INT NOT NULL, gross_clp INT, advances_clp INT, net_clp INT);
CREATE TABLE adjustments (id INT PRIMARY KEY AUTO_INCREMENT, worker_id INT NOT NULL, period_id INT NOT NULL, amount_clp INT NOT NULL, reason TEXT);
CREATE TABLE notifications (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, title VARCHAR(120), body TEXT, read_at DATETIME);
CREATE TABLE system_settings (id INT PRIMARY KEY AUTO_INCREMENT, setting_key VARCHAR(80) UNIQUE NOT NULL, setting_value VARCHAR(240) NOT NULL);
CREATE TABLE audit_logs (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT, module VARCHAR(80), action VARCHAR(80), entity_name VARCHAR(80), entity_id INT, old_values_json TEXT, new_values_json TEXT, ip_address VARCHAR(80), created_at DATETIME);
CREATE TABLE document_artifacts (id INT PRIMARY KEY AUTO_INCREMENT, path VARCHAR(240), artifact_type VARCHAR(80), created_at DATETIME);
CREATE TABLE api_logs (id INT PRIMARY KEY AUTO_INCREMENT, method VARCHAR(12), path VARCHAR(240), user_id INT, status_code INT, created_at DATETIME);
CREATE TABLE app_errors (id INT PRIMARY KEY AUTO_INCREMENT, module VARCHAR(80), message TEXT, handled BOOLEAN, created_at DATETIME);
